#!/bin/bash

readonly command_log=~/cmustag.todo
# see filetag.py -h for syntax
readonly command_parameters="$*"
readonly scripts_base=$(dirname $0)

# !!!! add "" to filepaths (to avoid file path problems, like blank spaces)
echo ${scripts_base}/filetag.py ${command_parameters} >> ${command_log}
